image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "$CI_COMMIT_REF_SLUG" # cache per branch
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - deploy

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test_and_coverage:
  stage: test
  script:
    - pip --quiet install -r requirements.txt
    - pip --quiet install .
    - pip --quiet install coverage
    - pip list
    - coverage run -m unittest discover -s ime_fgs/tests/
    - coverage html
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: coverage-report
    expire_in: 1 week
    paths:
     - coverage_html_report

run_demos:
  stage: test
  script:
    - pip --quiet install -r requirements.txt
    - pip --quiet install .
    - pip list
    - export PATH=$PATH:$(pwd)/tools/
    - run_demos_headless.sh

check_code_style:
  stage: test
  script:
    - pip --quiet install -r requirements.txt
    - pip --quiet install .
    - pip --quiet install pycodestyle
    - pip list
    - pycodestyle ime_fgs/
    
   
